// src/routes/(authenticated)/chat/+page.svelte
<script lang="ts">
	// export let data;
	// console.log('c-se', session);

	// const users = [
	// 	{
	// 		name: 'Test1',
	// 		href: 'tes1'
	// 	},
	// 	{
	// 		name: 'Test2',
	// 		href: 'tes2'
	// 	},
	// 	{
	// 		name: 'Test3',
	// 		href: 'tes3'
	// 	}
	// ];
</script>

<div class="min-h-svh p-5">
	<div class="mx-auto min-h-screen w-full max-w-7xl">
		<!-- <article class="rounded-lg border-2">
			<aside class="min-h-svh w-96 space-y-5 overflow-y-auto border-r p-5">
				<h2 class="border-b p-2 text-2xl font-medium">Hello, {session?.user?.name}</h2>
				<nav>
					<ul class="space-y-4">
						{#each users as user}
							<li class="hover:bg-primary-500 cursor-pointer rounded px-4 py-2">
								<a href="chat/{user?.href}" class="flex items-center gap-2">
									<User class="h-5 w-5" />
									<span>{user?.name}</span>
								</a>
							</li>
						{/each}
					</ul>
				</nav>
			</aside>
		</article> -->
		<article>
			<h2>Whatsapp Clone</h2>
		</article>
	</div>
</div>

// app/(protected)/chat/page.tsx
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { User } from "lucide-react";
import Link from "next/link";

export default function ChatPage() {
  return (
    <div className="bg-background p-5">
      <div className="max-w-7xl mx-auto">
        <Card className="max-w-5xl mx-auto">
          <CardContent>
            <div className="flex w-full h-[calc(100vh-12rem)] gap-4">
              <aside className="bg-primary/20 w-56 h-full p-5 space-y-4">
                <header className="p-2 border-b text-xl font-medium">
                  WhatsApp Clone
                </header>
                <ul className="space-y-4">
                  {Array.from({ length: 6 }).map((_, idx) => (
                    <li key={idx}>
                      <Link
                        className="flex items-center gap-2 px-4 py-2 rounded hover:bg-primary hover:text-primary-foreground"
                        href={`/chat/${idx + 1}`}
                      >
                        <User />
                        {`User - ${idx + 1}`}
                      </Link>
                    </li>
                  ))}
                </ul>
              </aside>
              <aside className="flex-1 bg-primary/40 h-full">
                <p>chat window</p>
              </aside>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
