// components/navbar.tsx
import { auth, signOut } from "@/auth";
import { LogOut, MessageCircle } from "lucide-react";
import Link from "next/link";
import { Button } from "./ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "./ui/dropdown-menu";

export default async function Navbar() {
  const session = await auth();
  return (
    <nav className="bg-background w-full p-4">
      <div className="max-w-7xl mx-auto">
        <div className="flex items-center justify-between">
          <h2 className="flex items-center gap-2 text-2xl font-medium">
            <MessageCircle />
            <Link href="/">Whastapp Clone</Link>
          </h2>
          <div>
            {session && session.user ? (
              <div className="flex items-center gap-4">
                <DropdownMenu>
                  <DropdownMenuTrigger>
                    <h2 className="text-2xl font-medium">
                      {session?.user?.name}
                    </h2>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent>
                    <DropdownMenuItem>Chat</DropdownMenuItem>
                    <DropdownMenuItem>Profile</DropdownMenuItem>
                    <DropdownMenuItem>Settings</DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
                <form
                  action={async () => {
                    "use server";
                    await signOut();
                  }}
                >
                  <Button variant={"destructive"}>
                    <LogOut />
                    Logout
                  </Button>
                </form>
              </div>
            ) : (
              <Button variant={"link"}>
                <Link href="/api/auth/signin">Continue with Google</Link>
              </Button>
            )}
          </div>
        </div>
      </div>
    </nav>
  );
}

// src/components/navbar.svelte
<script lang="ts">
	import { signOut } from '@auth/sveltekit/client';
	import { LogOut, MessageCircle } from 'lucide-svelte';
	const { session } = $props();
</script>

<nav class="w-full p-4">
	<div class="mx-auto max-w-7xl">
		<div class="flex items-center justify-between">
			<h2 class="flex items-center gap-1 text-2xl font-medium">
				<MessageCircle />
				<a href="/"> AurKya </a>
			</h2>
			{#if session && session?.user}
				<button type="button" class="btn preset-outlined-primary-500" onclick={signOut()}>
					<LogOut />
					Logout
				</button>
			{:else}
				<div class="flex items-center gap-4">
					<button type="button" class="btn">
						<a href="/login">Login</a>
					</button>
					<button type="button" class="btn bg-primary-500">
						<a href="/register">Register</a>
					</button>
				</div>
			{/if}
		</div>
	</div>
</nav>
